server:
  port: 9090

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-og8zp5ro.sql.tencentcdb.com:26956/movie
    name: movie_share
    password: Movie123456
    username: movie_share

