server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-og8zp5ro.sql.tencentcdb.com:26956/movie_test
    name: movie_share
    password: Movie123456
    username: movie_share



dataInit: false